### PR TITLE
Vagrantfile: Inconsistency in code of providers

### PR DESCRIPTION
**Pull request by elmar-hinz**
I wanted to make it 2 different pull requests, but github puts all into one, plus a merge. So please select the commits you want if any.

a) This change addresses the following issue:

https://github.com/webdevops/vagrant-development/issues/58

Not having a VmWare installation, I didn't test it.

b) In the second commit there is an update of the docs. The `/etc/sudoers` settings.

### CODE REVIEW

**Comment by mblaschke** [comment]
/etc/sudoers for OSX and Linux are different, that's why i just added link to vagrant documentation.

**Comment by elmar-hinz** [comment]
Vagrant docs:

```
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports
%admin ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```

Mine:

```
# Cmnd alias specification
Cmnd_Alias VAGRANT_EXPORTS_ADD = /usr/bin/tee -a /etc/exports
Cmnd_Alias VAGRANT_NFSD = /sbin/nfsd restart
Cmnd_Alias VAGRANT_EXPORTS_REMOVE = /usr/bin/sed -E -e /*/ d -ibak /etc/exports

# User privilege specification
root    ALL=(ALL) ALL
%admin  ALL=(ALL) ALL
%admin  ALL=(root) NOPASSWD: VAGRANT_EXPORTS_ADD, VAGRANT_NFSD, VAGRANT_EXPORTS_REMOVE
```

The Vagrant docs example is sparse. I was unsure if I can do the `%admin` setting twice or if I had to remove the existing entry. So my goal with this, is to make that more clear.

 It's not the place I like for experimenting. I would by frightened to lock myself out of the machine as admin.

**Comment by mblaschke** [comment]
Vagrant snipped should be safe :)
Never had issues with it

**Comment by elmar-hinz** [comment]
To me it was not clear how to apply the snippet. See above, why I was unsure. :)

Deleting `%admin  ALL=(ALL) ALL` would be a bad idea.

**Comment by mblaschke** [comment]
If we don't need the additional lines from documentation/INSTALL.md we can remove it and i can merge this PL :)

**Comment by elmar-hinz** [comment]
Feel free to do what you think right. :)

**Comment by mblaschke** [comment]
Would you remove the sudoers part? Then i can merge this PL :)

**Comment by elmar-hinz** [comment]
I did a history rewrite in a public repository, mine. Documents usually tell me not to do this. I don't know if I did something clever or something stupid. 

However, the pull request is changed to your liking. :)

**Pull request merged**
